package com.redhat.cajun.navy.rules;

import java.util.List;

import com.redhat.cajun.navy.rules.model.CommanderOverride;
import com.redhat.cajun.navy.rules.model.Incident;
import com.redhat.cajun.navy.rules.model.Mission;
import com.redhat.cajun.navy.rules.model.MissionAssignment;
import com.redhat.cajun.navy.rules.model.PotentialMissionAssignments;
import com.redhat.cajun.navy.rules.model.Responder;
import com.redhat.cajun.navy.rules.model.Status;

//TODO - @michael - using no loop on every rule is indicative of poorly though out rule design we should look into this

rule "Create the Mission Assignments"
    salience 100
    when
        $incident : Incident()
        $responder : Responder()
        not MissionAssignment( responder == $responder, incident == $incident )
    then
        insert( new MissionAssignment( $incident, $responder ) );
end

rule "The Responder can provide medical assitance"
    when
        $incident : Incident( medicalNeeded == true )
        $responder : Responder( hasMedical == true )
        $mission : MissionAssignment( incident == $incident, responder == $responder )
    then
    	System.out.println( "The Responder can provide medical assitance" );
        int currentScore = $mission.getCompatibilityScore();
        $mission.setCompatibilityScore( currentScore + 50 );
        
end

rule "The Responder can fit the number of people on their boat"
    when
        $incident : Incident( $numberOfPeople : numPeople )
        $responder : Responder( boatCapacity >= $numberOfPeople, $boatCapacity : boatCapacity )
        $mission : MissionAssignment( incident == $incident, responder == $responder )
    then
    	System.out.println( "The Responder can fit the number of people on their boat " + $boatCapacity + " " + $numberOfPeople );
        int currentScore = $mission.getCompatibilityScore();
		$mission.setCompatibilityScore( currentScore + 100 );
      
end

rule "The Responder can fit the EXACT number of people on their boat"
    when
        $incident : Incident( $numberOfPeople : numPeople )
        $responder : Responder( boatCapacity == $numberOfPeople )
        $mission : MissionAssignment( incident == $incident, responder == $responder )
    then
    	System.out.println( "The Responder can fit the EXACT number of people on their boat " + $incident );
        int currentScore = $mission.getCompatibilityScore();
		$mission.setCompatibilityScore( currentScore + 50 );

end

rule "Collect the Mission Assignments for Processing"
	salience -100
	when
		not PotentialMissionAssignments()
		$allAssignments : List() from collect( MissionAssignment() )
	then
		insert( new PotentialMissionAssignments( $allAssignments ) );
end

rule "Default Prioritization when no Command Override"
	salience -100
	when
		not CommanderOverride()
		$assignments : PotentialMissionAssignments( prioritized == false )
	then
		System.err.println( "Default prioritization algorithm, rules with a CommanderOverride would change this behavior" );
		modify( $assignments ){
			defaultPrioritization()
		}
end

rule "Assign the top mission"
	when
		not Mission()
		$assignments : PotentialMissionAssignments( prioritized == true )
	then
		insert( $assignments.getAssignedMission() );
end

rule "DEBUG - Print Mission Weights -- REMOVE LATER"
	salience -1000
	when
		$m : Mission( $incId : incidentId, respId : responderId )
		$i : Incident( id == $incId )
		$ma : MissionAssignment( incident == $i )
	then
		System.out.println( $m );
		System.out.println( $ma );
end